version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tsingleap-frontend
    ports:
      - "5173:80"  # 本地浏览器访问 http://localhost:5173 
    volumes:
      - ./Nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped